// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScraper.Data;

#nullable disable

namespace WebScraper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309231025_ExpandedSchema")]
    partial class ExpandedSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WebScraper.Models.ApiLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnEventId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ApiLinks");
                });

            modelBuilder.Entity("WebScraper.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Attendance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayOT")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayQ1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayQ2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayQ3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayQ4")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EspnEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeOT")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeQ1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeQ2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeQ3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeQ4")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HomeWinner")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeutralSite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VenueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("VenueId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebScraper.Models.Injury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnAthleteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InjuryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "EspnAthleteId")
                        .IsUnique();

                    b.ToTable("Injuries");
                });

            modelBuilder.Entity("WebScraper.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("College")
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WebScraper.Models.PlayerGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AdjQBR")
                        .HasColumnType("REAL");

                    b.Property<double>("DefensiveSacks")
                        .HasColumnType("REAL");

                    b.Property<int>("DefensiveTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraPointAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraPointsMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldGoalAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldGoalsMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fumbles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FumblesLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FumblesRecovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GrossAvgPuntYards")
                        .HasColumnType("REAL");

                    b.Property<int>("InterceptionTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterceptionYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interceptions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterceptionsCaught")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KickReturnTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KickReturnYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KickReturns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongFieldGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongKickReturn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongPunt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongPuntReturn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongReception")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongRushing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassesDefended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntReturnTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntReturnYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntReturns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntTouchbacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Punts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntsInside20")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QBHits")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("QBRating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReceivingTargets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceivingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceivingYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Receptions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SackYardsLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoloTackles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TacklesForLoss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalKickingPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTackles")
                        .HasColumnType("INTEGER");

                    b.Property<double>("YardsPerReception")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("WebScraper.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("WebScraper.Models.TeamGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefensiveTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDownsPassing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDownsPenalty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDownsRushing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FourthDownAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FourthDownMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FumblesLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterceptionsThrown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetPassingYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Penalties")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PenaltyYards")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PossessionTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RedZoneAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedZoneMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushingAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushingYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SackYardsLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SacksAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThirdDownAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThirdDownMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPlays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turnovers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("YardsPerPass")
                        .HasColumnType("REAL");

                    b.Property<double>("YardsPerRush")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("GameId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamGameStats");
                });

            modelBuilder.Entity("WebScraper.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGrass")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EspnId")
                        .IsUnique();

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("WebScraper.Models.ApiLink", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("ApiLinks")
                        .HasForeignKey("GameId");

                    b.HasOne("WebScraper.Models.Team", "Team")
                        .WithMany("ApiLinks")
                        .HasForeignKey("TeamId");

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebScraper.Models.Game", b =>
                {
                    b.HasOne("WebScraper.Models.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Venue", "Venue")
                        .WithMany("Games")
                        .HasForeignKey("VenueId");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("WebScraper.Models.Injury", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("Injuries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Player", "Player")
                        .WithMany("Injuries")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebScraper.Models.Player", b =>
                {
                    b.HasOne("WebScraper.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebScraper.Models.PlayerGameStats", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("PlayerStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Player", "Player")
                        .WithMany("GameStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebScraper.Models.TeamGameStats", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("TeamStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Team", "Team")
                        .WithMany("TeamStats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebScraper.Models.Game", b =>
                {
                    b.Navigation("ApiLinks");

                    b.Navigation("Injuries");

                    b.Navigation("PlayerStats");

                    b.Navigation("TeamStats");
                });

            modelBuilder.Entity("WebScraper.Models.Player", b =>
                {
                    b.Navigation("GameStats");

                    b.Navigation("Injuries");
                });

            modelBuilder.Entity("WebScraper.Models.Team", b =>
                {
                    b.Navigation("ApiLinks");

                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");

                    b.Navigation("Players");

                    b.Navigation("TeamStats");
                });

            modelBuilder.Entity("WebScraper.Models.Venue", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
