// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScraper.Data;

#nullable disable

namespace WebScraper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309231025_ExpandedSchema")]
    partial class ExpandedSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WebScraper.Models.ApiLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DiscoveredAt");

                    b.Property<string>("EndpointType")
                        .IsRequired();

                    b.Property<string>("EspnEventId");

                    b.Property<int?>("GameId");

                    b.Property<DateTime?>("LastAccessedAt");

                    b.Property<string>("RelationType")
                        .IsRequired();

                    b.Property<int?>("Season");

                    b.Property<int?>("TeamId");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.Property<int?>("Week");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ApiLinks");
                });

            modelBuilder.Entity("WebScraper.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Attendance");

                    b.Property<int?>("AwayOT");

                    b.Property<int?>("AwayQ1");

                    b.Property<int?>("AwayQ2");

                    b.Property<int?>("AwayQ3");

                    b.Property<int?>("AwayQ4");

                    b.Property<int?>("AwayScore");

                    b.Property<int>("AwayTeamId");

                    b.Property<string>("EspnEventId");

                    b.Property<DateTime>("GameDate");

                    b.Property<string>("GameStatus");

                    b.Property<int?>("HomeOT");

                    b.Property<int?>("HomeQ1");

                    b.Property<int?>("HomeQ2");

                    b.Property<int?>("HomeQ3");

                    b.Property<int?>("HomeQ4");

                    b.Property<int?>("HomeScore");

                    b.Property<int>("HomeTeamId");

                    b.Property<bool?>("HomeWinner");

                    b.Property<bool>("NeutralSite");

                    b.Property<int>("Season");

                    b.Property<int?>("VenueId");

                    b.Property<int>("Week");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("VenueId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebScraper.Models.Injury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BodyLocation")
                        .IsRequired();

                    b.Property<string>("Detail")
                        .IsRequired();

                    b.Property<string>("EspnAthleteId")
                        .IsRequired();

                    b.Property<int>("GameId");

                    b.Property<string>("InjuryType")
                        .IsRequired();

                    b.Property<int?>("PlayerId");

                    b.Property<string>("PlayerName")
                        .IsRequired();

                    b.Property<DateTime>("ReportDate");

                    b.Property<DateTime?>("ReturnDate");

                    b.Property<string>("Side")
                        .IsRequired();

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "EspnAthleteId")
                        .IsUnique();

                    b.ToTable("Injuries");
                });

            modelBuilder.Entity("WebScraper.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("College");

                    b.Property<string>("EspnId");

                    b.Property<string>("Height");

                    b.Property<int?>("JerseyNumber");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Position")
                        .IsRequired();

                    b.Property<int?>("TeamId");

                    b.Property<int?>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WebScraper.Models.PlayerGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("AdjQBR");

                    b.Property<double>("DefensiveSacks");

                    b.Property<int>("DefensiveTouchdowns");

                    b.Property<int>("ExtraPointAttempts");

                    b.Property<int>("ExtraPointsMade");

                    b.Property<int>("FieldGoalAttempts");

                    b.Property<int>("FieldGoalsMade");

                    b.Property<int>("Fumbles");

                    b.Property<int>("FumblesLost");

                    b.Property<int>("FumblesRecovered");

                    b.Property<int>("GameId");

                    b.Property<double>("GrossAvgPuntYards");

                    b.Property<int>("InterceptionTouchdowns");

                    b.Property<int>("InterceptionYards");

                    b.Property<int>("Interceptions");

                    b.Property<int>("InterceptionsCaught");

                    b.Property<int>("KickReturnTouchdowns");

                    b.Property<int>("KickReturnYards");

                    b.Property<int>("KickReturns");

                    b.Property<int>("LongFieldGoal");

                    b.Property<int>("LongKickReturn");

                    b.Property<int>("LongPunt");

                    b.Property<int>("LongPuntReturn");

                    b.Property<int>("LongReception");

                    b.Property<int>("LongRushing");

                    b.Property<int>("PassAttempts");

                    b.Property<int>("PassCompletions");

                    b.Property<int>("PassTouchdowns");

                    b.Property<int>("PassYards");

                    b.Property<int>("PassesDefended");

                    b.Property<int>("PlayerId");

                    b.Property<int>("PuntReturnTouchdowns");

                    b.Property<int>("PuntReturnYards");

                    b.Property<int>("PuntReturns");

                    b.Property<int>("PuntTouchbacks");

                    b.Property<int>("PuntYards");

                    b.Property<int>("Punts");

                    b.Property<int>("PuntsInside20");

                    b.Property<int>("QBHits");

                    b.Property<double?>("QBRating");

                    b.Property<int>("ReceivingTargets");

                    b.Property<int>("ReceivingTouchdowns");

                    b.Property<int>("ReceivingYards");

                    b.Property<int>("Receptions");

                    b.Property<int>("RushAttempts");

                    b.Property<int>("RushTouchdowns");

                    b.Property<int>("RushYards");

                    b.Property<int>("SackYardsLost");

                    b.Property<int>("Sacks");

                    b.Property<int>("SoloTackles");

                    b.Property<int>("TacklesForLoss");

                    b.Property<int>("TotalKickingPoints");

                    b.Property<int>("TotalTackles");

                    b.Property<double>("YardsPerReception");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("WebScraper.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Conference")
                        .IsRequired();

                    b.Property<string>("Division")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("WebScraper.Models.TeamGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DefensiveTouchdowns");

                    b.Property<int>("FirstDowns");

                    b.Property<int>("FirstDownsPassing");

                    b.Property<int>("FirstDownsPenalty");

                    b.Property<int>("FirstDownsRushing");

                    b.Property<int>("FourthDownAttempts");

                    b.Property<int>("FourthDownMade");

                    b.Property<int>("FumblesLost");

                    b.Property<int>("GameId");

                    b.Property<int>("InterceptionsThrown");

                    b.Property<int>("NetPassingYards");

                    b.Property<int>("PassAttempts");

                    b.Property<int>("PassCompletions");

                    b.Property<int>("Penalties");

                    b.Property<int>("PenaltyYards");

                    b.Property<string>("PossessionTime")
                        .IsRequired();

                    b.Property<int>("RedZoneAttempts");

                    b.Property<int>("RedZoneMade");

                    b.Property<int>("RushingAttempts");

                    b.Property<int>("RushingYards");

                    b.Property<int>("SackYardsLost");

                    b.Property<int>("SacksAgainst");

                    b.Property<int>("TeamId");

                    b.Property<int>("ThirdDownAttempts");

                    b.Property<int>("ThirdDownMade");

                    b.Property<int>("TotalPlays");

                    b.Property<int>("TotalYards");

                    b.Property<int>("Turnovers");

                    b.Property<double>("YardsPerPass");

                    b.Property<double>("YardsPerRush");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("GameId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamGameStats");
                });

            modelBuilder.Entity("WebScraper.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("EspnId")
                        .IsRequired();

                    b.Property<bool>("IsGrass");

                    b.Property<bool>("IsIndoor");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EspnId")
                        .IsUnique();

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("WebScraper.Models.ApiLink", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("ApiLinks")
                        .HasForeignKey("GameId");

                    b.HasOne("WebScraper.Models.Team", "Team")
                        .WithMany("ApiLinks")
                        .HasForeignKey("TeamId");

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebScraper.Models.Game", b =>
                {
                    b.HasOne("WebScraper.Models.Team", "AwayTeam")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Team", "HomeTeam")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Venue", "Venue")
                        .WithMany("Games")
                        .HasForeignKey("VenueId");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("WebScraper.Models.Injury", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("Injuries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Player", "Player")
                        .WithMany("Injuries")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebScraper.Models.Player", b =>
                {
                    b.HasOne("WebScraper.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebScraper.Models.PlayerGameStats", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("PlayerStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Player", "Player")
                        .WithMany("GameStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebScraper.Models.TeamGameStats", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("TeamStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Team", "Team")
                        .WithMany("TeamStats")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebScraper.Models.Game", b =>
                {
                    b.Navigation("ApiLinks");

                    b.Navigation("Injuries");

                    b.Navigation("PlayerStats");

                    b.Navigation("TeamStats");
                });

            modelBuilder.Entity("WebScraper.Models.Player", b =>
                {
                    b.Navigation("GameStats");

                    b.Navigation("Injuries");
                });

            modelBuilder.Entity("WebScraper.Models.Team", b =>
                {
                    b.Navigation("ApiLinks");

                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");

                    b.Navigation("Players");

                    b.Navigation("TeamStats");
                });

            modelBuilder.Entity("WebScraper.Models.Venue", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
