// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebScraper.Data;

#nullable disable

namespace WebScraper.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("WebScraper.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HashedKey");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("WebScraper.Models.ApiLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnEventId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("TeamId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ApiLinks");
                });

            modelBuilder.Entity("WebScraper.Models.ApiQueryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryString")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ApiKeyId", "Timestamp");

                    b.ToTable("ApiQueryLogs");
                });

            modelBuilder.Entity("WebScraper.Models.DataCorrection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("EntityType", "EntityId", "Field", "Status");

                    b.ToTable("DataCorrections");
                });

            modelBuilder.Entity("WebScraper.Models.DataQualityFinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RepairJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Severity");

                    b.HasIndex("RuleType", "EntityType", "EntityId");

                    b.ToTable("DataQualityFindings");
                });

            modelBuilder.Entity("WebScraper.Models.DatabasePushSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int>("StageOffset")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalRecordsPushed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabasePushSessions");
                });

            modelBuilder.Entity("WebScraper.Models.Franchise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalAbbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalAbbreviation")
                        .IsUnique();

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("WebScraper.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Attendance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayOT")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayQ1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayQ2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayQ3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayQ4")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BroadcastNetworks")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnEventId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeOT")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeQ1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeQ2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeQ3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeQ4")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeTeamSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HomeWinner")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeutralSite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VenueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamSeasonId");

                    b.HasIndex("HomeTeamSeasonId");

                    b.HasIndex("VenueId");

                    b.HasIndex("Season", "SeasonType", "Week", "HomeTeamSeasonId", "AwayTeamSeasonId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebScraper.Models.GameDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayResult")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EspnDriveId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OffensivePlays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeElapsed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Yards")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamSeasonId");

                    b.HasIndex("GameId", "EspnDriveId")
                        .IsUnique();

                    b.ToTable("GameDrives");
                });

            modelBuilder.Entity("WebScraper.Models.GameOdds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayMoneyline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeMoneyline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OverUnder")
                        .HasColumnType("REAL");

                    b.Property<int>("SnapshotType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sportsbook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Spread")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Sportsbook", "SnapshotType", "CapturedAt")
                        .IsUnique();

                    b.ToTable("GameOdds");
                });

            modelBuilder.Entity("WebScraper.Models.GameOfficial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameOfficials");
                });

            modelBuilder.Entity("WebScraper.Models.GameWeather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HighTemperatureF")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HumidityPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemperatureF")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindDirection")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WindSpeedMph")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("GameWeathers");
                });

            modelBuilder.Entity("WebScraper.Models.Injury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnAthleteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InjuryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GameId", "EspnAthleteId")
                        .IsUnique();

                    b.ToTable("Injuries");
                });

            modelBuilder.Entity("WebScraper.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("College")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EspnId")
                        .IsUnique()
                        .HasFilter("\"EspnId\" IS NOT NULL");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WebScraper.Models.PlayerGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AdjQBR")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefensiveSacks")
                        .HasColumnType("REAL");

                    b.Property<int>("DefensiveTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtraPointAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExtraPointsMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldGoalAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldGoalsMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fumbles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FumblesLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FumblesRecovered")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("GrossAvgPuntYards")
                        .HasColumnType("REAL");

                    b.Property<int>("InterceptionTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterceptionYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Interceptions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterceptionsCaught")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KickReturnTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KickReturnYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KickReturns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongFieldGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongKickReturn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongPunt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongPuntReturn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongReception")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LongRushing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassesDefended")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntReturnTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntReturnYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntReturns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntTouchbacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Punts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntsInside20")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QBHits")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("QBRating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReceivingTargets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceivingTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceivingYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Receptions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SackYardsLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sacks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoloTackles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TacklesForLoss")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalKickingPoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTackles")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("YardsPerReception")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGameStats");
                });

            modelBuilder.Entity("WebScraper.Models.PlayerTeamSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamSeasonId");

                    b.HasIndex("PlayerId", "TeamSeasonId")
                        .IsUnique();

                    b.ToTable("PlayerTeamSeasons");
                });

            modelBuilder.Entity("WebScraper.Models.ScoringPlay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clock")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnPlayId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeScore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoringType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamSeasonId");

                    b.HasIndex("GameId", "EspnPlayId")
                        .IsUnique();

                    b.ToTable("ScoringPlays");
                });

            modelBuilder.Entity("WebScraper.Models.ScrapeEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("ScrapeEvents");
                });

            modelBuilder.Entity("WebScraper.Models.ScrapeJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DependsOnJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentJobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnJobId");

                    b.HasIndex("ParentJobId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("ScrapeJobs");
                });

            modelBuilder.Entity("WebScraper.Models.SeasonCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualGames")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExpectedGames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesWithInjuries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesWithOdds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesWithPlayerStats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesWithTeamStats")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Season");

                    b.HasIndex("Season", "SeasonType", "Week")
                        .IsUnique();

                    b.ToTable("SeasonCoverages");
                });

            modelBuilder.Entity("WebScraper.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("WebScraper.Models.TeamGameStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefensiveTouchdowns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("FirstDowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDownsPassing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDownsPenalty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstDownsRushing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FourthDownAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FourthDownMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FumblesLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterceptionsThrown")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetPassingYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassCompletions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Penalties")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PenaltyYards")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PossessionTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RedZoneAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RedZoneMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushingAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RushingYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SackYardsLost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SacksAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamSeasonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThirdDownAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThirdDownMade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPlays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalYards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turnovers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("YardsPerPass")
                        .HasColumnType("REAL");

                    b.Property<double>("YardsPerRush")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TeamSeasonId");

                    b.HasIndex("GameId", "TeamSeasonId")
                        .IsUnique();

                    b.ToTable("TeamGameStats");
                });

            modelBuilder.Entity("WebScraper.Models.TeamSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Conference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId", "Season")
                        .IsUnique();

                    b.ToTable("TeamSeasons");
                });

            modelBuilder.Entity("WebScraper.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSourceFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSourceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EspnId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGrass")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EspnId")
                        .IsUnique();

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("WebScraper.Models.ApiLink", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("ApiLinks")
                        .HasForeignKey("GameId");

                    b.HasOne("WebScraper.Models.Team", "Team")
                        .WithMany("ApiLinks")
                        .HasForeignKey("TeamId");

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebScraper.Models.Game", b =>
                {
                    b.HasOne("WebScraper.Models.TeamSeason", "AwayTeamSeason")
                        .WithMany("AwayGames")
                        .HasForeignKey("AwayTeamSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.TeamSeason", "HomeTeamSeason")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeTeamSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Venue", "Venue")
                        .WithMany("Games")
                        .HasForeignKey("VenueId");

                    b.Navigation("AwayTeamSeason");

                    b.Navigation("HomeTeamSeason");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("WebScraper.Models.GameDrive", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("Drives")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.TeamSeason", "TeamSeason")
                        .WithMany()
                        .HasForeignKey("TeamSeasonId");

                    b.Navigation("Game");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("WebScraper.Models.GameOdds", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("Odds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("WebScraper.Models.GameOfficial", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("Officials")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("WebScraper.Models.GameWeather", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithOne("Weather")
                        .HasForeignKey("WebScraper.Models.GameWeather", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("WebScraper.Models.Injury", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("Injuries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Player", "Player")
                        .WithMany("Injuries")
                        .HasForeignKey("PlayerId");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebScraper.Models.Player", b =>
                {
                    b.HasOne("WebScraper.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebScraper.Models.PlayerGameStats", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("PlayerStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.Player", "Player")
                        .WithMany("GameStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WebScraper.Models.PlayerTeamSeason", b =>
                {
                    b.HasOne("WebScraper.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.TeamSeason", "TeamSeason")
                        .WithMany("PlayerRosterEntries")
                        .HasForeignKey("TeamSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("WebScraper.Models.ScoringPlay", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("ScoringPlays")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.TeamSeason", "TeamSeason")
                        .WithMany()
                        .HasForeignKey("TeamSeasonId");

                    b.Navigation("Game");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("WebScraper.Models.TeamGameStats", b =>
                {
                    b.HasOne("WebScraper.Models.Game", "Game")
                        .WithMany("TeamStats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebScraper.Models.TeamSeason", "TeamSeason")
                        .WithMany("TeamStats")
                        .HasForeignKey("TeamSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("TeamSeason");
                });

            modelBuilder.Entity("WebScraper.Models.TeamSeason", b =>
                {
                    b.HasOne("WebScraper.Models.Franchise", "Franchise")
                        .WithMany("TeamSeasons")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("WebScraper.Models.Franchise", b =>
                {
                    b.Navigation("TeamSeasons");
                });

            modelBuilder.Entity("WebScraper.Models.Game", b =>
                {
                    b.Navigation("ApiLinks");

                    b.Navigation("Drives");

                    b.Navigation("Injuries");

                    b.Navigation("Odds");

                    b.Navigation("Officials");

                    b.Navigation("PlayerStats");

                    b.Navigation("ScoringPlays");

                    b.Navigation("TeamStats");

                    b.Navigation("Weather");
                });

            modelBuilder.Entity("WebScraper.Models.Player", b =>
                {
                    b.Navigation("GameStats");

                    b.Navigation("Injuries");
                });

            modelBuilder.Entity("WebScraper.Models.Team", b =>
                {
                    b.Navigation("ApiLinks");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("WebScraper.Models.TeamSeason", b =>
                {
                    b.Navigation("AwayGames");

                    b.Navigation("HomeGames");

                    b.Navigation("PlayerRosterEntries");

                    b.Navigation("TeamStats");
                });

            modelBuilder.Entity("WebScraper.Models.Venue", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
